// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: certificate.sql

package sqlc

import (
	"context"
)

const createCertificate = `-- name: CreateCertificate :one
INSERT INTO certificate (
    id,
    name,
    cert_type,
    algorithm,
    key_size,
    pem_data,
    metadata
) VALUES (
    ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, created_at, name, cert_type, algorithm, key_size, pem_data, metadata
`

type CreateCertificateParams struct {
	ID        string  `db:"id" json:"id"`
	Name      string  `db:"name" json:"name"`
	CertType  string  `db:"cert_type" json:"cert_type"`
	Algorithm string  `db:"algorithm" json:"algorithm"`
	KeySize   *int64  `db:"key_size" json:"key_size"`
	PemData   string  `db:"pem_data" json:"pem_data"`
	Metadata  *string `db:"metadata" json:"metadata"`
}

// CreateCertificate
//
//	INSERT INTO certificate (
//	    id,
//	    name,
//	    cert_type,
//	    algorithm,
//	    key_size,
//	    pem_data,
//	    metadata
//	) VALUES (
//	    ?, ?, ?, ?, ?, ?, ?
//	)
//	RETURNING id, created_at, name, cert_type, algorithm, key_size, pem_data, metadata
func (q *Queries) CreateCertificate(ctx context.Context, arg CreateCertificateParams) (Certificate, error) {
	row := q.db.QueryRowContext(ctx, createCertificate,
		arg.ID,
		arg.Name,
		arg.CertType,
		arg.Algorithm,
		arg.KeySize,
		arg.PemData,
		arg.Metadata,
	)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Name,
		&i.CertType,
		&i.Algorithm,
		&i.KeySize,
		&i.PemData,
		&i.Metadata,
	)
	return i, err
}

const deleteCertificate = `-- name: DeleteCertificate :exec
DELETE FROM certificate
WHERE name = ?
`

// DeleteCertificate
//
//	DELETE FROM certificate
//	WHERE name = ?
func (q *Queries) DeleteCertificate(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteCertificate, name)
	return err
}

const getCertificate = `-- name: GetCertificate :one
SELECT id, created_at, name, cert_type, algorithm, key_size, pem_data, metadata
FROM certificate
WHERE name = ?
`

// GetCertificate
//
//	SELECT id, created_at, name, cert_type, algorithm, key_size, pem_data, metadata
//	FROM certificate
//	WHERE name = ?
func (q *Queries) GetCertificate(ctx context.Context, name string) (Certificate, error) {
	row := q.db.QueryRowContext(ctx, getCertificate, name)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Name,
		&i.CertType,
		&i.Algorithm,
		&i.KeySize,
		&i.PemData,
		&i.Metadata,
	)
	return i, err
}

const getCertificatesByType = `-- name: GetCertificatesByType :many
SELECT id, created_at, name, cert_type, algorithm, key_size, pem_data, metadata
FROM certificate
WHERE cert_type = ?
ORDER BY created_at DESC
`

// GetCertificatesByType
//
//	SELECT id, created_at, name, cert_type, algorithm, key_size, pem_data, metadata
//	FROM certificate
//	WHERE cert_type = ?
//	ORDER BY created_at DESC
func (q *Queries) GetCertificatesByType(ctx context.Context, certType string) ([]Certificate, error) {
	rows, err := q.db.QueryContext(ctx, getCertificatesByType, certType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Certificate{}
	for rows.Next() {
		var i Certificate
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Name,
			&i.CertType,
			&i.Algorithm,
			&i.KeySize,
			&i.PemData,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCertificates = `-- name: ListCertificates :many
SELECT id, created_at, name, cert_type, algorithm, key_size, pem_data, metadata
FROM certificate
ORDER BY created_at DESC
`

// ListCertificates
//
//	SELECT id, created_at, name, cert_type, algorithm, key_size, pem_data, metadata
//	FROM certificate
//	ORDER BY created_at DESC
func (q *Queries) ListCertificates(ctx context.Context) ([]Certificate, error) {
	rows, err := q.db.QueryContext(ctx, listCertificates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Certificate{}
	for rows.Next() {
		var i Certificate
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Name,
			&i.CertType,
			&i.Algorithm,
			&i.KeySize,
			&i.PemData,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCertificate = `-- name: UpdateCertificate :one
UPDATE certificate
SET
    pem_data = ?,
    metadata = ?
WHERE name = ?
RETURNING id, created_at, name, cert_type, algorithm, key_size, pem_data, metadata
`

type UpdateCertificateParams struct {
	PemData  string  `db:"pem_data" json:"pem_data"`
	Metadata *string `db:"metadata" json:"metadata"`
	Name     string  `db:"name" json:"name"`
}

// UpdateCertificate
//
//	UPDATE certificate
//	SET
//	    pem_data = ?,
//	    metadata = ?
//	WHERE name = ?
//	RETURNING id, created_at, name, cert_type, algorithm, key_size, pem_data, metadata
func (q *Queries) UpdateCertificate(ctx context.Context, arg UpdateCertificateParams) (Certificate, error) {
	row := q.db.QueryRowContext(ctx, updateCertificate, arg.PemData, arg.Metadata, arg.Name)
	var i Certificate
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Name,
		&i.CertType,
		&i.Algorithm,
		&i.KeySize,
		&i.PemData,
		&i.Metadata,
	)
	return i, err
}
