// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: credential.sql

package sqlc

import (
	"context"
	"time"
)

const createCredential = `-- name: CreateCredential :one
INSERT INTO credential (
    id,
    token,
    expires_at
) VALUES (
    ?, ?, ?
)
RETURNING id, created_at, expires_at, token
`

type CreateCredentialParams struct {
	ID        string     `db:"id" json:"id"`
	Token     string     `db:"token" json:"token"`
	ExpiresAt *time.Time `db:"expires_at" json:"expires_at"`
}

// CreateCredential
//
//	INSERT INTO credential (
//	    id,
//	    token,
//	    expires_at
//	) VALUES (
//	    ?, ?, ?
//	)
//	RETURNING id, created_at, expires_at, token
func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) (Credential, error) {
	row := q.db.QueryRowContext(ctx, createCredential, arg.ID, arg.Token, arg.ExpiresAt)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Token,
	)
	return i, err
}

const deleteCredential = `-- name: DeleteCredential :exec
DELETE FROM credential
WHERE token = ?
`

// DeleteCredential
//
//	DELETE FROM credential
//	WHERE token = ?
func (q *Queries) DeleteCredential(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteCredential, token)
	return err
}

const getCredential = `-- name: GetCredential :one
SELECT id, created_at, expires_at, token
FROM credential
WHERE token = ?
`

// GetCredential
//
//	SELECT id, created_at, expires_at, token
//	FROM credential
//	WHERE token = ?
func (q *Queries) GetCredential(ctx context.Context, token string) (Credential, error) {
	row := q.db.QueryRowContext(ctx, getCredential, token)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Token,
	)
	return i, err
}

const listCredentials = `-- name: ListCredentials :many
SELECT id, created_at, expires_at, token
FROM credential
ORDER BY created_at DESC
`

// ListCredentials
//
//	SELECT id, created_at, expires_at, token
//	FROM credential
//	ORDER BY created_at DESC
func (q *Queries) ListCredentials(ctx context.Context) ([]Credential, error) {
	rows, err := q.db.QueryContext(ctx, listCredentials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Credential{}
	for rows.Next() {
		var i Credential
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.Token,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCredential = `-- name: UpdateCredential :one
UPDATE credential
SET
    expires_at = ?
WHERE id = ?
RETURNING id, created_at, expires_at, token
`

type UpdateCredentialParams struct {
	ExpiresAt *time.Time `db:"expires_at" json:"expires_at"`
	ID        string     `db:"id" json:"id"`
}

// UpdateCredential
//
//	UPDATE credential
//	SET
//	    expires_at = ?
//	WHERE id = ?
//	RETURNING id, created_at, expires_at, token
func (q *Queries) UpdateCredential(ctx context.Context, arg UpdateCredentialParams) (Credential, error) {
	row := q.db.QueryRowContext(ctx, updateCredential, arg.ExpiresAt, arg.ID)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Token,
	)
	return i, err
}
