// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: log.sql

package sqlc

import (
	"context"
)

const createLog = `-- name: CreateLog :one
INSERT INTO log (
    id,
    event,
    msg,
    requested_url,
    remote_addr
) VALUES (
    ?, ?, ?, ?, ?
)
RETURNING id, created_at, event, msg, requested_url, remote_addr
`

type CreateLogParams struct {
	ID           string  `db:"id" json:"id"`
	Event        string  `db:"event" json:"event"`
	Msg          string  `db:"msg" json:"msg"`
	RequestedUrl *string `db:"requested_url" json:"requested_url"`
	RemoteAddr   *string `db:"remote_addr" json:"remote_addr"`
}

// CreateLog
//
//	INSERT INTO log (
//	    id,
//	    event,
//	    msg,
//	    requested_url,
//	    remote_addr
//	) VALUES (
//	    ?, ?, ?, ?, ?
//	)
//	RETURNING id, created_at, event, msg, requested_url, remote_addr
func (q *Queries) CreateLog(ctx context.Context, arg CreateLogParams) (Log, error) {
	row := q.db.QueryRowContext(ctx, createLog,
		arg.ID,
		arg.Event,
		arg.Msg,
		arg.RequestedUrl,
		arg.RemoteAddr,
	)
	var i Log
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Event,
		&i.Msg,
		&i.RequestedUrl,
		&i.RemoteAddr,
	)
	return i, err
}

const deleteLogs = `-- name: DeleteLogs :exec
DELETE FROM log
`

// DeleteLogs
//
//	DELETE FROM log
func (q *Queries) DeleteLogs(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteLogs)
	return err
}

const listLogs = `-- name: ListLogs :many
SELECT id, created_at, event, msg, requested_url, remote_addr
FROM log
ORDER BY created_at DESC
`

// ListLogs
//
//	SELECT id, created_at, event, msg, requested_url, remote_addr
//	FROM log
//	ORDER BY created_at DESC
func (q *Queries) ListLogs(ctx context.Context) ([]Log, error) {
	rows, err := q.db.QueryContext(ctx, listLogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Log{}
	for rows.Next() {
		var i Log
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Event,
			&i.Msg,
			&i.RequestedUrl,
			&i.RemoteAddr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
