// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"
)

type Certificate struct {
	ID        string     `db:"id" json:"id"`
	CreatedAt *time.Time `db:"created_at" json:"created_at"`
	Name      string     `db:"name" json:"name"`
	CertType  string     `db:"cert_type" json:"cert_type"`
	Algorithm string     `db:"algorithm" json:"algorithm"`
	KeySize   *int64     `db:"key_size" json:"key_size"`
	PemData   string     `db:"pem_data" json:"pem_data"`
	Metadata  *string    `db:"metadata" json:"metadata"`
}

type Log struct {
	ID           string     `db:"id" json:"id"`
	CreatedAt    *time.Time `db:"created_at" json:"created_at"`
	Event        string     `db:"event" json:"event"`
	Msg          string     `db:"msg" json:"msg"`
	RequestedUrl *string    `db:"requested_url" json:"requested_url"`
	RemoteAddr   *string    `db:"remote_addr" json:"remote_addr"`
}

type Permission struct {
	ID               string     `db:"id" json:"id"`
	CreatedAt        *time.Time `db:"created_at" json:"created_at"`
	TokenID          string     `db:"token_id" json:"token_id"`
	SecretKeyPattern string     `db:"secret_key_pattern" json:"secret_key_pattern"`
}

type Secret struct {
	ID        string     `db:"id" json:"id"`
	CreatedAt *time.Time `db:"created_at" json:"created_at"`
	Key       string     `db:"key" json:"key"`
	Value     string     `db:"value" json:"value"`
}

type Token struct {
	ID        string     `db:"id" json:"id"`
	CreatedAt *time.Time `db:"created_at" json:"created_at"`
	ExpiresAt *time.Time `db:"expires_at" json:"expires_at"`
	Token     string     `db:"token" json:"token"`
}

type User struct {
	ID        string     `db:"id" json:"id"`
	CreatedAt *time.Time `db:"created_at" json:"created_at"`
	Username  string     `db:"username" json:"username"`
	Password  string     `db:"password" json:"password"`
}
