// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"
)

type Log struct {
	ID        string     `db:"id" json:"id"`
	CreatedAt *time.Time `db:"created_at" json:"created_at"`
	Event     string     `db:"event" json:"event"`
	Msg       string     `db:"msg" json:"msg"`
}

type Permission struct {
	ID               string     `db:"id" json:"id"`
	CreatedAt        *time.Time `db:"created_at" json:"created_at"`
	CredentialID     string     `db:"credential_id" json:"credential_id"`
	SecretKeyPattern string     `db:"secret_key_pattern" json:"secret_key_pattern"`
}

type Secret struct {
	ID        string     `db:"id" json:"id"`
	CreatedAt *time.Time `db:"created_at" json:"created_at"`
	Key       string     `db:"key" json:"key"`
	Value     string     `db:"value" json:"value"`
}

type Token struct {
	ID        string       `db:"id" json:"id"`
	CreatedAt *time.Time   `db:"created_at" json:"created_at"`
	ExpiresAt sql.NullTime `db:"expires_at" json:"expires_at"`
	Token     string       `db:"token" json:"token"`
}

type User struct {
	ID        string     `db:"id" json:"id"`
	CreatedAt *time.Time `db:"created_at" json:"created_at"`
	Username  string     `db:"username" json:"username"`
	Password  string     `db:"password" json:"password"`
}
