// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: permission.sql

package sqlc

import (
	"context"
)

const createPermission = `-- name: CreatePermission :one
INSERT INTO permission (
    id,
    token_id,
    secret_key_pattern
) VALUES (
    ?, ?, ?
)
RETURNING id, created_at, token_id, secret_key_pattern
`

type CreatePermissionParams struct {
	ID               string `db:"id" json:"id"`
	TokenID          string `db:"token_id" json:"token_id"`
	SecretKeyPattern string `db:"secret_key_pattern" json:"secret_key_pattern"`
}

// CreatePermission
//
//	INSERT INTO permission (
//	    id,
//	    token_id,
//	    secret_key_pattern
//	) VALUES (
//	    ?, ?, ?
//	)
//	RETURNING id, created_at, token_id, secret_key_pattern
func (q *Queries) CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error) {
	row := q.db.QueryRowContext(ctx, createPermission, arg.ID, arg.TokenID, arg.SecretKeyPattern)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.TokenID,
		&i.SecretKeyPattern,
	)
	return i, err
}

const deletePermission = `-- name: DeletePermission :exec
DELETE FROM permission
WHERE id = ?
`

// DeletePermission
//
//	DELETE FROM permission
//	WHERE id = ?
func (q *Queries) DeletePermission(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePermission, id)
	return err
}

const listPermissions = `-- name: ListPermissions :many
SELECT id, created_at, token_id, secret_key_pattern
FROM permission
ORDER BY created_at DESC
`

// ListPermissions
//
//	SELECT id, created_at, token_id, secret_key_pattern
//	FROM permission
//	ORDER BY created_at DESC
func (q *Queries) ListPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.QueryContext(ctx, listPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.TokenID,
			&i.SecretKeyPattern,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionsByTokenId = `-- name: ListPermissionsByTokenId :many
SELECT id, created_at, token_id, secret_key_pattern
FROM permission
WHERE token_id = ?
ORDER BY created_at DESC
`

// ListPermissionsByTokenId
//
//	SELECT id, created_at, token_id, secret_key_pattern
//	FROM permission
//	WHERE token_id = ?
//	ORDER BY created_at DESC
func (q *Queries) ListPermissionsByTokenId(ctx context.Context, tokenID string) ([]Permission, error) {
	rows, err := q.db.QueryContext(ctx, listPermissionsByTokenId, tokenID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.TokenID,
			&i.SecretKeyPattern,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePermission = `-- name: UpdatePermission :one
UPDATE permission
SET
    secret_key_pattern = ?
WHERE id = ?
RETURNING id, created_at, token_id, secret_key_pattern
`

type UpdatePermissionParams struct {
	SecretKeyPattern string `db:"secret_key_pattern" json:"secret_key_pattern"`
	ID               string `db:"id" json:"id"`
}

// UpdatePermission
//
//	UPDATE permission
//	SET
//	    secret_key_pattern = ?
//	WHERE id = ?
//	RETURNING id, created_at, token_id, secret_key_pattern
func (q *Queries) UpdatePermission(ctx context.Context, arg UpdatePermissionParams) (Permission, error) {
	row := q.db.QueryRowContext(ctx, updatePermission, arg.SecretKeyPattern, arg.ID)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.TokenID,
		&i.SecretKeyPattern,
	)
	return i, err
}
