// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: secret.sql

package sqlc

import (
	"context"
)

const createSecret = `-- name: CreateSecret :one
INSERT INTO secret (
    id,
    key,
    value
) VALUES (
    ?, ?, ?
)
RETURNING id, created_at, "key", value
`

type CreateSecretParams struct {
	ID    string `db:"id" json:"id"`
	Key   string `db:"key" json:"key"`
	Value string `db:"value" json:"value"`
}

// CreateSecret
//
//	INSERT INTO secret (
//	    id,
//	    key,
//	    value
//	) VALUES (
//	    ?, ?, ?
//	)
//	RETURNING id, created_at, "key", value
func (q *Queries) CreateSecret(ctx context.Context, arg CreateSecretParams) (Secret, error) {
	row := q.db.QueryRowContext(ctx, createSecret, arg.ID, arg.Key, arg.Value)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Key,
		&i.Value,
	)
	return i, err
}

const deleteSecret = `-- name: DeleteSecret :exec
DELETE FROM secret
WHERE key = ?
`

// DeleteSecret
//
//	DELETE FROM secret
//	WHERE key = ?
func (q *Queries) DeleteSecret(ctx context.Context, key string) error {
	_, err := q.db.ExecContext(ctx, deleteSecret, key)
	return err
}

const getSecret = `-- name: GetSecret :one
SELECT id, created_at, "key", value
FROM secret
WHERE key = ?
`

// GetSecret
//
//	SELECT id, created_at, "key", value
//	FROM secret
//	WHERE key = ?
func (q *Queries) GetSecret(ctx context.Context, key string) (Secret, error) {
	row := q.db.QueryRowContext(ctx, getSecret, key)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Key,
		&i.Value,
	)
	return i, err
}

const listSecrets = `-- name: ListSecrets :many
SELECT id, created_at, "key", value
FROM secret
ORDER BY created_at DESC
`

// ListSecrets
//
//	SELECT id, created_at, "key", value
//	FROM secret
//	ORDER BY created_at DESC
func (q *Queries) ListSecrets(ctx context.Context) ([]Secret, error) {
	rows, err := q.db.QueryContext(ctx, listSecrets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Secret{}
	for rows.Next() {
		var i Secret
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Key,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSecret = `-- name: UpdateSecret :one
UPDATE secret
SET
    value = ?
WHERE key = ?
RETURNING id, created_at, "key", value
`

type UpdateSecretParams struct {
	Value string `db:"value" json:"value"`
	Key   string `db:"key" json:"key"`
}

// UpdateSecret
//
//	UPDATE secret
//	SET
//	    value = ?
//	WHERE key = ?
//	RETURNING id, created_at, "key", value
func (q *Queries) UpdateSecret(ctx context.Context, arg UpdateSecretParams) (Secret, error) {
	row := q.db.QueryRowContext(ctx, updateSecret, arg.Value, arg.Key)
	var i Secret
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Key,
		&i.Value,
	)
	return i, err
}
