// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: token.sql

package sqlc

import (
	"context"
	"time"
)

const createToken = `-- name: CreateToken :one
INSERT INTO token (
    id,
    token,
    expires_at
) VALUES (
    ?, ?, ?
)
RETURNING id, created_at, expires_at, token
`

type CreateTokenParams struct {
	ID        string     `db:"id" json:"id"`
	Token     string     `db:"token" json:"token"`
	ExpiresAt *time.Time `db:"expires_at" json:"expires_at"`
}

// CreateToken
//
//	INSERT INTO token (
//	    id,
//	    token,
//	    expires_at
//	) VALUES (
//	    ?, ?, ?
//	)
//	RETURNING id, created_at, expires_at, token
func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (Token, error) {
	row := q.db.QueryRowContext(ctx, createToken, arg.ID, arg.Token, arg.ExpiresAt)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Token,
	)
	return i, err
}

const deleteToken = `-- name: DeleteToken :exec
DELETE FROM token
WHERE id = ?
`

// DeleteToken
//
//	DELETE FROM token
//	WHERE id = ?
func (q *Queries) DeleteToken(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteToken, id)
	return err
}

const getToken = `-- name: GetToken :one
SELECT id, created_at, expires_at, token
FROM token
WHERE id = ?
`

// GetToken
//
//	SELECT id, created_at, expires_at, token
//	FROM token
//	WHERE id = ?
func (q *Queries) GetToken(ctx context.Context, id string) (Token, error) {
	row := q.db.QueryRowContext(ctx, getToken, id)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Token,
	)
	return i, err
}

const getTokenByToken = `-- name: GetTokenByToken :one
SELECT id, created_at, expires_at, token
FROM token
WHERE token = ?
`

// GetTokenByToken
//
//	SELECT id, created_at, expires_at, token
//	FROM token
//	WHERE token = ?
func (q *Queries) GetTokenByToken(ctx context.Context, token string) (Token, error) {
	row := q.db.QueryRowContext(ctx, getTokenByToken, token)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Token,
	)
	return i, err
}

const listTokens = `-- name: ListTokens :many
SELECT id, created_at, expires_at, token
FROM token
ORDER BY created_at DESC
`

// ListTokens
//
//	SELECT id, created_at, expires_at, token
//	FROM token
//	ORDER BY created_at DESC
func (q *Queries) ListTokens(ctx context.Context) ([]Token, error) {
	rows, err := q.db.QueryContext(ctx, listTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Token{}
	for rows.Next() {
		var i Token
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.Token,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateToken = `-- name: UpdateToken :one
UPDATE token
SET
    expires_at = ?
WHERE id = ?
RETURNING id, created_at, expires_at, token
`

type UpdateTokenParams struct {
	ExpiresAt *time.Time `db:"expires_at" json:"expires_at"`
	ID        string     `db:"id" json:"id"`
}

// UpdateToken
//
//	UPDATE token
//	SET
//	    expires_at = ?
//	WHERE id = ?
//	RETURNING id, created_at, expires_at, token
func (q *Queries) UpdateToken(ctx context.Context, arg UpdateTokenParams) (Token, error) {
	row := q.db.QueryRowContext(ctx, updateToken, arg.ExpiresAt, arg.ID)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Token,
	)
	return i, err
}
