// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package sqlc

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO user (
    id,
    username,
    password
) VALUES (
    ?, ?, ?
)
RETURNING id, created_at, username, password
`

type CreateUserParams struct {
	ID       string `db:"id" json:"id"`
	Username string `db:"username" json:"username"`
	Password string `db:"password" json:"password"`
}

// CreateUser
//
//	INSERT INTO user (
//	    id,
//	    username,
//	    password
//	) VALUES (
//	    ?, ?, ?
//	)
//	RETURNING id, created_at, username, password
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.ID, arg.Username, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Username,
		&i.Password,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM user
WHERE id = ?
`

// DeleteUser
//
//	DELETE FROM user
//	WHERE id = ?
func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, created_at, username, password
FROM user
WHERE id = ?
`

// GetUser
//
//	SELECT id, created_at, username, password
//	FROM user
//	WHERE id = ?
func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Username,
		&i.Password,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, created_at, username, password
FROM user
WHERE username = ?
`

// GetUserByUsername
//
//	SELECT id, created_at, username, password
//	FROM user
//	WHERE username = ?
func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Username,
		&i.Password,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, created_at, username, password
FROM user
ORDER BY created_at DESC
`

// ListUsers
//
//	SELECT id, created_at, username, password
//	FROM user
//	ORDER BY created_at DESC
func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Username,
			&i.Password,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE user
SET
    password = ?
WHERE id = ?
RETURNING id, created_at, username, password
`

type UpdateUserParams struct {
	Password string `db:"password" json:"password"`
	ID       string `db:"id" json:"id"`
}

// UpdateUser
//
//	UPDATE user
//	SET
//	    password = ?
//	WHERE id = ?
//	RETURNING id, created_at, username, password
func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser, arg.Password, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Username,
		&i.Password,
	)
	return i, err
}
